defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: true

timeZone: "UTC"

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
  goldmark:
    duplicateResourceFiles: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    noHl: false
    style: native
    tabWidth: 4
  diagrams:
    enable: true
    theme: default

disableKinds:
#- "404"
- home
#- robotsTXT
- RSS
#- section
#- sitemap
- taxonomy
- term

enableGitInfo: true

sitemap:
  filename: "sitemap.xml"
  priority: 0.75

params:
  analytics:
    google: XXXX
    yandex: XXXX
  # GitHub repository link for editing a page and opening issues.
  github_repo: https://github.com/deckhouse/delivery-kit
  # Show "Edit this page" link
  showedit: true
  remoteAssetURL: /includes/

  # Enable Lunr.js offline search
  offlineSearch: false

  # Global relevant links.
  links:

module:
  imports:
    # Site templates
    - path: github.com/deckhouse/hugo-web-product-module
      #mounts:
      #  - source: docs/api
      #    target: content/reference/api/engine/version
      #    includeFiles: "*.yaml"

languages:
  en:
    disabled: false
    languageDirection: ""
    languageName: ""
    title: Deckhouse Delivery Kit
    weight: 0
    baseURL: https://deckhouse.io/products/delivery-kit/
    params:
      publicRootURL: https://deckhouse.io
      description: ""
  ru:
    disabled: false
    languageDirection: ""
    languageName: ""
    weight: 1
    title: Deckhouse Delivery Kit
    baseURL: https://deckhouse.ru/products/delivery-kit/
    params:
      publicRootURL: https://deckhouse.io
      description: ""
