defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: true

timeZone: "UTC"

disableKinds:
#- "404"
#- home
#- robotsTXT
- RSS
#- section
#- sitemap
- taxonomy
- term

enableGitInfo: true

sitemap:
  filename: "sitemap.xml"
  priority: 0.75

params:
  analytics:
    google: XXXX
    yandex: XXXX
  # GitHub repository link for editing a page and opening issues.
  github_repo: https://github.com/deckhouse/deckhouse-delivery-kit
  # Show "Edit this page" link
  showedit: true
  remoteAssetURL: /includes/

  # Enable Lunr.js offline search
  offlineSearch: false

  # Global relevant links.
  links:

menus:
  # Site header menu
  main:
  - name: Get started
    pageRef: /get-started/
    weight: 1
  - name: Guides
    pageRef: /guides/
    weight: 2
  - name: Manuals
    pageRef: /manuals/
    weight: 3
  - name: Reference
    pageRef: /reference/
    weight: 4

module:
  imports:
    # Site templates
    - path: github.com/deckhouse/hugo-web-product-module
      #mounts:
      #  - source: docs/api
      #    target: content/reference/api/engine/version
      #    includeFiles: "*.yaml"

languages:
  en:
    disabled: false
    languageDirection: ""
    languageName: ""
    title: Deckhouse Delivery Kit
    weight: 0
    baseURL: https://deckhouse.io/products/delivery-kit/
    params:
      publicRootURL: https://deckhouse.io
      description: ""
  ru:
    disabled: false
    languageDirection: ""
    languageName: ""
    weight: 1
    title: Deckhouse Delivery Kit
    baseURL: https://deckhouse.ru/products/delivery-kit/
    params:
      publicRootURL: https://deckhouse.ru
      description: ""
